### ISSUE TITLE
ERC777

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#163]
Transition ERC677 -> ERC777 for all tokens Aragon generates

https://github.com/ethereum/EIPs/issues/777

**Comment by Quazia** [comment]
I've started some work on this and will try and get it finished between other tasks over the next few days. I'll check in if I'm not making progress.

**Comment by izqui** [comment]
Awesome! I want to merge it this week as we want to code freeze on Monday and we also have to modify aragon-apps to use the new standard :)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd059ad0facf064a6c109a3865bf2aaa5830ab45111ec4f2d918e977ee1819d60](https://etherscan.io/tx/0xd059ad0facf064a6c109a3865bf2aaa5830ab45111ec4f2d918e977ee1819d60)

**Comment by izqui** [comment]
@Quazia any status update? :) If you can do it this week then I will focus on other things for the freeze. Would really appreciate it :)
