### ISSUE TITLE
Permission parameters

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#164]
Right now all apps in an organization require the same permission level to upgrade them, `UPGRADE_APPS_ROLE`.

We should decide whether to allow to create special permissions for upgrading certain apps, as some apps are could be more critical than others.

**Comment by onbjerg** [comment]
Do you have something in mind that would allow this to happen *without* making an edge-case for the permission escalation algorithm? Or at least, the edge-case should be simple to implement client-side.

**Comment by izqui** [comment]
Lets look into *the edge-case should be simple to implement client-side* as I cannot think about how can we implement it without making it a edge-case. Maybe we can create standard edge-cases for the ACL, so apps can add evaluable parameters to roles.

**Comment by izqui** [comment]
We can generalize this to allow certain permissions to be parametrized. This way different app upgrades would be just an implementation of this. Actually the kernel itself could be a special case of this. 

Going to start research on this front soon but this is how I imagine this to look:

```
contract FinanceApp is App {
   function makePayment(address to, uint256 amount) auth(MAKE_PAYMENT_ROLE, paymentAuthPredicate, amount) { ... }

  function paymentAuthPredicate(bytes paramData, bytes permissionData) view returns (bool) {
      uint maxAmountForSender = magicFunction(permissionData);
      uint paymentAmount = magicFunction2(paramData)

      return paymentAmount <= maxAmountForSender;
   }
}
