### ISSUE TITLE
Run tests in geth and parity

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#171]
Right now the test suite only runs on ganache-cli (former testrpc). Gearing up to mainnet deployment, we need to be running our tests in real nodes where code will eventually be deployed. 

Great inspiration for how to do this right can be taken from the https://github.com/JoinColony/colonySale repo

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9e5e8943f39bb6b5d41f5fb3e1fc7907f889848531e9ff8606a3ff7ae1193f4d](https://etherscan.io/tx/0x9e5e8943f39bb6b5d41f5fb3e1fc7907f889848531e9ff8606a3ff7ae1193f4d)

**Comment by fgimenez** [comment]
hi @izqui! I'd like to give it a try. This is my very first issue, already set up on status.im, anything else needed to get started?

**Comment by izqui** [comment]
Sweet! Nothing needed to get started!

**Comment by fgimenez** [comment]
@cpurta you are doing a wonderful job on https://github.com/aragon/aragon-apps/pull/66! I'm starting with this issue today but every question that has arisen for me so far is solved in your PR :) So please feel free to take this one too once you are done, I think that your current work could be adapted to this issue very nicely.

**Comment by trislit** [comment]
Are you still looking at testing this? Are you attempting to test with payments through the front end api or just straight sendtocontract calls?

**Comment by nadavhollander** [comment]
@izqui Came across this across the interwebz because we're looking do the exact same thing at Dharma.  Have you found any good leads on how to do this?  I'm not sure how to recreate TestRPC functionality like `evm_increaseTime` in Geth / Parity

**Comment by sohkai** [comment]
@nadavhollander That's a good question, I'm not sure if @cpurta has run into that issue with https://github.com/aragon/aragon-apps/pull/66 yet...

There's an open spec that's under some discussion: https://github.com/ethereum/interfaces/issues/4.

**Comment by cpurta** [comment]
@nadavhollander I have ran into the same issue with Geth and Parity. They do not support that method in the RPC for good reason. Currently for testing you could not run any tests that make those calls when using those clients. I know that is a pretty bad solution to the problem but it may be better than the alternative.

The alternative would be making changes to one/both clients to support the method and maintaining a up to date branch with the master (or releases).

**Comment by sohkai** [comment]
@nadavhollander Something to try (we kind of use this strategy) is avoiding use of any of the time utilities in ganache and using a mocked contract to set the time instead.

**Comment by aj07** [comment]
@izqui is this bounty still open for new contributors ? If yes, I would like to work on this

**Comment by sohkai** [comment]
He @aj07; this has been put on standby for a while and @cpurta's done a really good job with #186 already.

**Comment by sohkai** [comment]
Closing; as mentioned in #186, this is not a short term priority at the moment.
