### ISSUE TITLE
Add 'anyone can perform this action' notion to ACL

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#172]
If the last address in Ethereum's address space (`0xffff...ffff` or `address(uint256(-1))`) is given a permission (can perform an action), that means that any address is allowed to perform that action, effectively having an open bylaw. 

This is needed for `apm` governance.

**Comment by onbjerg** [comment]
**Kernel.sol L160**
```js
return permissions[_entity][_app][_role] || permissions[address(-1)][_app][_role];
```

Done

**Comment by izqui** [comment]
Yup, I would make it a constant to make it prettier, but that's pretty much it.

**Comment by onbjerg** [comment]
Yeah of course
