### ISSUE TITLE
Add changelog and release

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#180]

**Comment by PascalPrecht** [comment]
As discussed in https://github.com/aragon/aragon-cli/pull/164#issuecomment-411308967 this can be easily achieved by sticking to a commit message convention that can be parsed to generate changelogs out from that automatically.

One convention that can be used is described here: https://github.com/aragon/aragon-cli/pull/164#issuecomment-411381825

**Comment by sohkai** [comment]
@PascalPrecht I'd love to start adopting something like conventional-changelog to make this more automated! Difficult part is to start agreeing, so an AGP would be a good start :).

We can also start deploying commit hooks, CI hooks, etc. to make sure we adhere to these standards, but as you can imagine, that's been on the backburner ;).

**Comment by PascalPrecht** [comment]
> Difficult part is to start agreeing, so an AGP would be a good start :)

Okay, I'll give this a spin then.

> We can also start deploying commit hooks, CI hooks, etc. to make sure we adhere to these standards, but as you can imagine, that's been on the backburner ;)

Yes. I'd suggest we take it one step at a time. I'll go ahead and try to create my first AGP and then we take it from there. Once the community came to consensus, really the bread and butter is to stay disciplined and use those conventions everybody agreed on. 

Adding the tooling is then the smallest problem I guess. We should also make sure to introduce dedicated contribution guideline (in case they don't exist yet).

Lemme give the AGP a try. I'll update this thread once done.

**Comment by izqui** [comment]
Completely support this, thanks @PascalPrecht for leading the initiative! looking fwd to the AGP

**Comment by PascalPrecht** [comment]
Here's a first attempt: https://github.com/aragon/governance/issues/31

**Comment by luisivan** [comment]
Stale issue, closing now

**Comment by luisivan** [comment]
(BTW thanks @pascalprecht, seems like we are using a commit message convention now, plus we will be automating changelogs soon)

**Comment by PascalPrecht** [comment]
That's awesome, happy to see conventions being applied! 👏
