### ISSUE TITLE
Rename project to aragon-os

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#183]
`aragon-core` isn't too descriptive of what is really here, specially because we implement AragonOS. 

Also Aragon Core is how we refer to the organization that develops Aragon right now as well as the product that allows to run organizations. 

I also like that we would have two repos, the core `aragon-os` and then the applications that run on top of it on`aragon-apps`.

**Comment by linuxchip** [comment]
@izqui i think aragon-os and aragon-apps are appropriate. They are good

**Comment by onbjerg** [comment]
I'd prefer not using the hyphen (aragonos as opposed to aragon-os) since we write it out as aragonOS or AragonOS

**Comment by luisivan** [comment]
I'd still use the hyphen for consistency. Thoughts?

**Comment by izqui** [comment]
Would look way clunkier, also we never write aragon os nor aragon-os, we always do AragonOS or aragonOS (we need consistency on whether we capitalize the 'A')

<img width="255" alt="2018-01-15 at 10 24 29 am" src="https://user-images.githubusercontent.com/447328/34935510-6d4d3710-f9de-11e7-9eae-c0f650e5379d.png">

**Comment by luisivan** [comment]
I agree this looks better. Re capitalizing the A, I think that since we use capital A everywhere, we should do the same for AragonOS
