### ISSUE TITLE
Forwarder apps (implementing IForwarder) have to implement isForwarder

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragonOS#195]
It is essential for forwarders to return true for calls to `isForwarder`, but since our change to interfaces, every forwarder app have to implement this method manually.

Also, there is no test for forwarders.

**Comment by sohkai** [comment]
Closing since we've implemented `isForwarder` during the upgrade to 3.0 in aragon-apps.

Added a note to https://github.com/aragon/aragonOS/pull/204 for explicitly documenting the interface.
