### ISSUE TITLE
Create BytesHelpers contract to concentrate all spread out logic

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#207]
@sohkai in #205:
> We now have two slightly different ways of doing this uint[] to bytes conversion (see canPerform() in Kernel), so I'm wondering if it'd be nice to add this as toBytes() somewhere. Maybe we can move some of the more general helpers in ScriptHelpers (e.g. uint256At, addressAt, uint32At, locationOf) to another library like BytesHelpers?

**Comment by emi-silva** [comment]
Beginner here. @sohkai mentions two uint[] to bytes conversions: the first one is in apps/AragonApp.sol:25. The second one, if I'm not mistaken, is in acl/ACL.sol:161. I'd like to have more context on how these conversions are different from each other and why they are needed in the first place. I need as much context as you can provide. Thank you.

**Comment by Quazia** [comment]
ScriptHelpers.sol just went under major revision, does it still make sense to move logic into BytesHelpers? Should we close this?

**Comment by izqui** [comment]
I think we can close it as most of that code got removed after upgrading to solc 0.4.24.
