### ISSUE TITLE
Compile and publish ABIs as part of NPM pre-publish

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#213]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x0da441044dd6c2f9171d25a0126ee41b5a71326e4a9363b7e2a3b27c8aed49ba](https://etherscan.io/tx/0x0da441044dd6c2f9171d25a0126ee41b5a71326e4a9363b7e2a3b27c8aed49ba)

**Comment by cpurta** [comment]
@izqui I think that I may take this one on. Is the idea here to just have a pre-publish script compile the contracts with truffle and everything in the `build/contracts` folder gets published to the npm registry?

**Comment by onbjerg** [comment]
@cpurta That would definitely be ideal. Make sure to still keep `build` in `.gitignore` since those files might be a super good source of merge conflicts 🙏
