### ISSUE TITLE
Add kernel.newAPMAppInstance() to instantiate apps with the latest APM version

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#214]
Instead of taking an `_appBase` as a parameter, it would take the address of the ENS (or the ENS address could be saved as a reference in the app mapping too), and it would try to find an APM repo with that node and set the latest version of the contract as the app base.

**Comment by izqui** [comment]
Some code I wrote for doing this in a template:
```
function latestVersionAppBase(bytes32 appId) internal view returns (address base) {
        Repo repo = Repo(PublicResolver(ens().resolver(appId)).addr(appId));
        (,base,) = repo.getLatest();

        return base;
  }
```

**Comment by sohkai** [comment]
Closing; this does not seem that important for most aragonOS users.
