### ISSUE TITLE
Rename ACL functions to reduce verbosity

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#223]
Proposed changes: 

```
acl.createPermission(...) -> acl.create(...)
acl.grantPermission(...) -> acl.grant(...)
...
```

IMO it made sense when the ACL was inside the kernel to use more descriptive names, but now that it is its own component, it isn't needed IMO.

Thoughts?

**Comment by sohkai** [comment]
💓

**Comment by onbjerg** [comment]
reported for making too much sense

**Comment by NFhbar** [comment]
https://github.com/aragon/aragonOS/pull/301

**Comment by sohkai** [comment]
Closing as this didn't make it to `aragonOS@4` and would mean another breaking interface change.
