### ISSUE TITLE
Fixing syntax highlighting

### ISSUE THREAD

**Issue by rbharath** [aragon/aragonOS#231]
I recently submitted PR https://github.com/aragon/aragonOS/pull/230 which attempted to fix syntax highlighting in the aragon repo. (Thanks for the quick merge Aragon team!). Unfortunately, this appears not to have fixed syntax highlighting.

After a little investigation, I think I've found the cause. Aragon uses `pragma solidity` statements of this form:
```
pragma solidity 0.4.18;
```
For example, the file https://github.com/aragon/aragonOS/blob/dev/contracts/acl/ACL.sol has this line at the top. However, the Github linguist feature set is set up to only recognize statements of the form `pragma solidity ^0.4.18;` with the extra `^` at top. When I modified this same file in my fork to have the modified pragma, all of a sudden syntax highlighting works. https://github.com/rbharath/aragonOS/blob/dev/contracts/acl/ACL.sol in my fork (with the modified pragma) has functional syntax highlighting.

I see a couple possible fixes. The first is to swap to pragma statements of the form `pragma solidity ^0.4.18`. Are there any particular downsides to this swap?

If aragon's current pragma statements are a necessary feature, we will have to submit a PR fix to Github's linguist addition for solidity, which might require more effort.

**Comment by bingen** [comment]
There are reasons to keep the compiler version fixed:

https://consensys.github.io/smart-contract-best-practices/recommendations/#lock-pragmas-to-specific-compiler-version

**Comment by bingen** [comment]
Btw, it seems it does actually work. Look at `dev` branch, where the PR was merged to (instead of `master`).

**Comment by rbharath** [comment]
@bingen Sorry, my bad on this one! Looks like the syntax highlighting change was just taking a long time to propagate.

**Comment by bingen** [comment]
@rbharath No problem! Actually, thanks for fixing it! ;-)
