### ISSUE TITLE
Add a dev guide

### ISSUE THREAD

**Issue by sohkai** [aragon/aragonOS#240]
Note some details / gotchas we currently have floating in our heads on developing for aragonOS (and extensions). The wiki might be a good place to put this.

Some good things to document:
- [ ] Guidelines for pragmas (interfaces / user extendable vs. core contracts)
- [ ] App design (single, predictable functionality)

**Comment by verdverm** [comment]
#204

**Comment by sohkai** [comment]
Closed by #488.
