### ISSUE TITLE
Edits and corrections to aOS doc

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#280]
Even though #204 was merged it wasn't reviewed by a native english speaker, so there could be some errors!

**Comment by Kyrrui** [comment]
I will look it over 👍

**Comment by Kyrrui** [comment]
I have reviewed the document and made comments @ #204 . When I get time I'll make a PR out of the comments.

**Comment by Qkyrie** [comment]
Hi @izqui, is this issue already solved? If not, would it be ok if we added some funding to it with fundrequest.io?

**Comment by sohkai** [comment]
@Qkyrie we haven't yet, so please feel free to :).
