### ISSUE TITLE
DAOFactory: loosen version requirements

### ISSUE THREAD

**Issue by ewingrj** [aragon/aragonOS#341]
In general app developers are able to choose their version of solidity, unless they want to use `DAOFactory`.

We use `DAOFactory` as a base for our deployment factory, however we are either forced to use `0.4.18` for everything, or do 2 separate compilations (1 for apps & 1 for factory).

It would be nice if DAOFactory version wasn't pinned, or if there was an interface provided

**Comment by izqui** [comment]
We tend to pin mission critical contracts to a specific version. In my opinion the best way forward would be to provide an interface for `DAOFactory` which can have a loose pin.

**Comment by sohkai** [comment]
Closing for general interface improvements in https://github.com/aragon/aragonOS/issues/577.
