### ISSUE TITLE
Provide uint64 time helpers

### ISSUE THREAD

**Issue by sohkai** [aragon/aragonOS#361]
We normally assume `uint64` is enough for time (it should be...), but to be explicitly safe, we can also provide a safe conversion utility for `uint256 -> uint64`.

We should also add base contracts to supply both time and block number so the interface is consistent (and maybe even provide a mocked version for easier testing) in apps.

**Comment by bingen** [comment]
For reference: https://github.com/ConsenSys/aragon-apps-audit-repo/issues/38
