### ISSUE TITLE
Add tests to compare size of compiled byte code between changesets

### ISSUE THREAD

**Issue by sohkai** [aragon/aragonOS#370]
Not quite sure how we'd get the old compiled byte code to diff against the new one... but should be possible.

Could be done via a custom Github app, Danger (e.g. see how [react's dangerfile does the git actions](https://github.com/facebook/react/blob/master/dangerfile.js), or as part of a travis build.

**Comment by izqui** [comment]
I think something like [Danger](http://danger.systems/js/) could be a great tool for this

**Comment by sohkai** [comment]
Partly done through #387.

Now we just have to figure out how to automate this...
