### ISSUE TITLE
Provide migration guide from aragonOS 3 to aragonOS 4

### ISSUE THREAD

**Issue by sohkai** [aragon/aragonOS#404]
We should have a `MIGRATION.md` that provides details on what app developers need to change in their apps to migration to aragonOS 4.

**Comment by izqui** [comment]
Ups, actually this is not done yet.

**Comment by bingen** [comment]
We can copy it from here:
https://github.com/aragon/aragonOS/wiki/aragonOS-4:-Updates-to-aragonOS-and-aragon-apps#aragon-apps

**Comment by cjyabraham** [comment]
Looks like this can be closed @sohkai

**Comment by sohkai** [comment]
Closed by https://github.com/aragon/hack/pull/56.
