### ISSUE TITLE
ParserError: Expected identifier, got 'LParen'

### ISSUE THREAD

**Issue by arquimed** [aragon/aragonOS#405]
Hi there, 

I am getting the following error when doing "aragon run":

✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ❯ Deploy contract
     ⠦ Compile contracts
       Deploy 'CNM' to network
     Automatically bump version
     Determine contract address for version
     Building frontend
     Prepare files for publishing
     Generate application artifact
     Publish test12.aragonpm.eth
     Fetch published repo
   Create DAO
   Open DAO
Error parsing /home/democritus/Documents/Projects/ScipioPlatform/test12/contracts/CNM.sol: ParsedContract.sol:56:16: ParserError: Expected identifier, got 'LParen'
    constructor(address _tokenAddress) public{
               ^
Compilation failed. See above.

Doing "truffle version" on main project directory returns:
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)

It seems as if I the aragonOS was using a former version of solc or truffle that does not allow for constructor and emit syntax.

Is it a version problem or this syntax is not allowed in an Aragon Dapp?

Thanks!

**Comment by izqui** [comment]
Until the aragonOS 4 release can be used in the ACL (coming soon), the supported Solidity version is v0.4.18, which doesn't allow the `constructor` nor `emit` syntax. The truffle version that is actually used to compile your app when using the CLI is v4.0.5.
