### ISSUE TITLE
Ensure KernelProxy integrity

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#457]
As mentioned in https://github.com/aragon/aragon/issues/462 (under Bonus > History integrity), there is currently no way to detect if a KernelProxy was ever pointed to a malicious Kernel `implementation` (other that checking debug traces for all transactions in Ethereum for calls to the KernelProxy 🙃) that may have installed a backdoor in the storage of some contract.

In order to detect this, we cannot rely on saving any storage in the KernelProxy contract as a malicious Kernel implementation could clean up this storage after it is done adding the backdoor and removes itself as the implementation.

The only possible way to mitigate this is by having the KernelProxy emit a log with its implementation address every time that it forwards a call to its implementation. These logs cannot be tampered with by any malicious Kernel implementation, even if the first implementation is malicious (provided that the KernelProxy code is checked and it is not malicious itself).

Alternatively, being able to track down the creation of a KernelProxy to a trusted DAOFactory address would provide the same guarantee, as if the kernel is ever upgraded to a malicious Kernel, it will emit an untamperable log.

**Comment by sohkai** [comment]
Couldn't we just detect all `SetApp(CORE_NAMESPACE, KERNEL_ID, <addr>)` events and check that the the addresses are ones we expect? If they ever set it to something non-official (maybe compare to registered kernels in APM?), it'd be a pretty big red flag.

**Comment by izqui** [comment]
Yep that would work but only if the `DAOFactory` that deployed the DAO is trusted, si we can be sure that the Kernel would have emitted an event if ever changed to another implementation.

**Comment by sohkai** [comment]
Rather than emitting an event on every proxy invocation, I would rather add a `SetApp` event to the `KernelProxy` constructor so we don't have to look for the `DAOFactory`.

**Comment by izqui** [comment]
That should work as well!

**Comment by izqui** [comment]
We will need to look at `DAOFactory` for currently deployed DAOs, but we should make the change to the `KernelProxy` asap
