### ISSUE TITLE
Interfaces only expose a small subset of the public/external contract functions

### ISSUE THREAD

**Issue by ewingrj** [aragon/aragonOS#458]
It would be great if the interfaces exposed all public/external contract functions.

In the current state, users must either implement their own interface in order to expose the necessary functions, or import the implementation contract itself.

Importing the impl contract is not ideal b/c these contracts are typically pinned, thus forcing any contract importing the impl contract to use the same solidity version.

**Comment by sohkai** [comment]
We generally try to keep the interfaces minimal, and only include the most important parts of an interface.

The current `Kernel` and `ACL` have a number of interfaces which are "non-standard", but we could probably provide an "interop" interface contract for them.

Are there any interfaces in particular you'd like to expose?

**Comment by sohkai** [comment]
> To deploy the app, the current practice is to use a Kit (correct me if I'm wrong). These kits often need to create/grant permissions on the ACL, but these functions aren't exposed via the interface. The kit will need to import ACL instead of IACL thus forcing the use of the aragonOS pinned solidity version.

Hmm, yes, this is a definite area of improvement. Being able to smoothly use kits with the current implementation of the `Kernel` and `ACL` is quite important (might live elsewhere, like beside [`kits-base`](https://github.com/aragon/dao-kits/blob/master/kits/base/contracts/KitBase.sol)).

**Comment by sohkai** [comment]
Closing for general interface improvements in https://github.com/aragon/aragonOS/issues/577.
