### ISSUE TITLE
Add testing utilities for aOS 4

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragonOS#462]
Since testing apps is not so-and-so since aOS 4 (rhymes if you say it out loud) because app implementations are autopetrified, a bunch of test utilities to Make Testing Easier Again™️ would be very cool.

Importing could be something like

```js
const utils = require('@aragon/os/utils')
```

I guess one util would be to create a kernel proxy, one for an app proxy, and another would be to assign some permissions to an address (such that it is easier to test that the correct roles are in place).

**Comment by izqui** [comment]
This would be really neat. It could also be a good opportunity to bring some of [these test helpers](https://github.com/aragon/aragon-apps/tree/master/shared/test-helpers) to aOS as well.

**Comment by sohkai** [comment]
This has been more or less done in [`contract-helpers`](https://github.com/aragon/contract-helpers).
