### ISSUE TITLE
Add radspec strings to ens/ENSSubdomainRegistrar.sol

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#477]

**Comment by usetech-llc** [comment]
I'd like to help with this one, but need a bit more information: Are talking about smart comments like in natspec?

**Comment by sohkai** [comment]
@usetech-llc Yes, using the `@notice` field in natspec, although with a bit of radspec processing added in (so things like parameters are interpolated in the resulting string). You can see an example here: https://github.com/aragon/aragonOS/blob/dev/contracts/kernel/Kernel.sol#L38.

**Comment by usetech-llc** [comment]
Awesome, thank you! Consider it done :) I'll also take on similar [issue # 478](https://github.com/aragon/aragonOS/issues/478)

**Comment by gregzaitsev** [comment]
It's done, you can merge my PR. But I have one question: Unit tests have passed, though I did not find unit test specific to radspec in your Kernel.sol example. How would you test it? (Unit Test or manually)

**Comment by gregzaitsev** [comment]
BTW, there is an issue with CLA bot that you are using. I created an issue in their repository, here is the reference:
https://github.com/cla-assistant/cla-assistant/issues/419

**Comment by sohkai** [comment]
We don't really test the radspec strings at this point, but that could be something we start testing...

**Comment by sohkai** [comment]
Closed by #487
