### ISSUE TITLE
Add radspec strings to factory/*.sol

### ISSUE THREAD

**Issue by izqui** [aragon/aragonOS#478]

**Comment by usetech-llc** [comment]
This is similar to [issue # 477](https://github.com/aragon/aragonOS/issues/477), I'd like to help with both.

**Comment by gregzaitsev** [comment]
This is done, you may merge it now, here is the PR: https://github.com/aragon/aragonOS/pull/498

But I have a question about DAOFactory: Looks like variable reg created on this line (58):

            EVMScriptRegistry reg = regFactory.newEVMScriptRegistry(dao);

Is not used futher. Is this EVMScriptRegistry instance used at all?

**Comment by sohkai** [comment]
It is used to generate an event immediately afterwards: https://github.com/aragon/aragonOS/blob/1db770d0c1ef11140b5c25dd20bb8471944ba68b/contracts/factory/DAOFactory.sol#L59.

**Comment by sohkai** [comment]
Completed with #498.
