### ISSUE TITLE
Create CONTRIBUTING doc for this repo

### ISSUE THREAD

**Issue by sohkai** [aragon/aragonOS#485]
Also include branch convention: https://forum.aragon.org/t/documenting-the-git-branch-convention-on-smart-contract-repos/599

**Comment by ianbrt** [comment]
Hey @sohkai I want to start contributing to the project, maybe I can start here. I was thinking I can use this [contributing template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) and add a few things I saw in other [aragon repos](https://github.com/aragon/hack/blob/master/CONTRIBUTING.md). Let me know what do you think and I can fork and PR :)

**Comment by sohkai** [comment]
@ianbrt That template looks really good! Would love a PR, and I can help add additional details as needed :).
