### ISSUE TITLE
Aragon Voting - Insufficient Budget Bug

### ISSUE THREAD

**Issue by mariapaulafn** [aragon/aragonOS#520]
https://www.dropbox.com/s/wayj5hlt3mpy8yo/Aragon%20Voting.mov?dl=0 - video

In this video, you will see the issue we encountered with the budget distribution feature within the Aragon interface

Practical example:
Imagine that our DAO has a budget of 1 ETH. We create 2 votes regarding how to spend this money.  However, there is no message or warning when funds are not sufficient in the UX, in case of approval of both votes Participants in the absence of this information, may vote YES for both votes-. This leads to an error and can open attack vectors on the DAO itself.

How can we fix it? 
The easiest way to fix it is to lock funds until the voting ends:
If the DAO balance is Y ETH and there is a vote to withdraw X ETH, then you cannot create another vote to withdraw more than Y-X ETH. 
However, this approach will not prevent the following attack:
The attacker can always create a vote to withdraw Y ETH. As soon as the vote ends (obviously, unsuccessfully), he may create a new vote. In this case, the DAO loses the ability to manage its funds and is essentially paralyzed. Therefore, while the aforementioned approach can help with one type of behavior, it won’t be an ideal solution.

Another approach is to focus on the UX instead of on-chain changes.  In this case, a warning should be added stating there are not enough funds to approve both votes.

<img width="613" alt="Screenshot 2019-05-03 at 11 04 36" src="https://user-images.githubusercontent.com/27913589/57128332-5c706280-6d93-11e9-8299-70968c07bc2e.png">

Figure 1: In this case, it is necessary to show that the user can’t choose “Yes” for both  Vote #7 and Vote #8. 

As a next step, we can add additional logic to the Voting app: 
If voting competes for funds distribution, Voting “Yes” in one vote lead to automatic “No” in another. 
But we’re not sure whether this feature can be implemented because as of now, the Voting app and Finance app work absolutely asynchronous.

**Comment by sohkai** [comment]
@mariapaulafn I would not consider this a contract-level bug; the contracts are working as intended. Locking funds when creating a vote is a potential feature that could be added, but it would be in the realm of a new application or [trigger](https://forum.aragon.org/t/aragon-triggers-enhanced-forwarding-interface-for-improved-composability/451).

> A warning should be added stating there are not enough funds to approve both votes.
> If voting competes for funds distribution, Voting “Yes” in one vote lead to automatic “No” in another.

Both of these would be difficult to do generically in the Voting app. The best we could likely do: 

- Use optimistic UX / [pending action information](https://forum.aragon.org/t/showing-pending-forwarded-actions-in-apps/709) in the Finance app to tell the user their second withdraw may not have enough funds
- Tell users in the Voting app that the vote, if executed now, would fail
