### ISSUE TITLE
Question: Should it be possible to continue importing truffle-config.js from external aragon apps?

### ISSUE THREAD

**Issue by ottodevs** [aragon/aragonOS#535]
Previously, extending truffle-config from @aragon/os, seemed to become somehow common and useful practice , as seen on most [aragon core apps](https://github.com/aragon/aragon-apps/blob/master/apps/survey/truffle.js)

But this seems not possible anymore unless `truffle-hdwallet-provider` and `ethereumjs-testrpc` that are required from that truffle-config, get bundled into the module or moved from `devDependencies` to `dependencies` or `peerDependencies` since these devDeps are not installed automatically when running `npm i`' on apps that inherit this handy truffle-config

Any idea or recommendation to do from now? does it make sense to continue providing the truffle-config as external convenient default?

The usefulness of this feature gets increased if we think that even from the local config is possible to extend the inherited one by reassigning the needed variables.

I think it would be nice for the whole dev community to reuse as much code as we can, and truffle-config seems like a good candidate for me, as a dev I liked the previous approach and saved me tons of time :)

EDIT: Thinking about that, it seems like a reasonable solution to put these requires behind environment conditions, if that makes sense... I currently dunno if this actually possible

**Comment by ottodevs** [comment]
Sorry, forget about this, I was using the wrong @aragon/core library

**Comment by sohkai** [comment]
While it'll stay possible in aragonOS 4, we'll eventually move the truffle config onto its own package so there are less packages depending on aragonOS solely for the truffle config (see #318).
