### ISSUE TITLE
AragonApp - duplicate check for `onlyInit` in `app.initialize()` when calling `initialized()`

### ISSUE THREAD

**Issue by tintinweb** [aragon/aragonOS#537]
Hi,

just a minor observation. This is not really an issue as this method is only called once on init and it is probably even better to leave the `onlyInit` modifier there just to make it explicit that this can only be called if uninitialized (and it may prevent worse things from happening if someone forgets to call `initialized()` but thats another story :) ) .

* https://hack.aragon.org/docs/tutorial.html
* https://hack.aragon.org/docs/aragonos-building#constructor-and-initialization
> AragonApp exposes the onlyInit modifier to protect a function from being called after initialized() has been completed and the auth(), authP(), and isInitialized modifiers to protect against a function from being called before the initialization is complete.

both articles state that `app.initialize()` should be decorated with `onlyInit`, however if the function is calling `initialized()` then this check is performed twice as `initialized()` is decorated with `onlyInit` as well.

https://github.com/aragon/aragonOS/blob/28ad69d4b92414018f087cadd48a8f3e280c5b7a/contracts/common/Initializable.sol#L48

**Comment by sohkai** [comment]
@tintinweb Good catch, but I think it's good practice to leave the `onlyInit` modifier. It is also not _that_ expensive 😉.

There's a bit of history here, as we used to not require apps be initialized if they didn't have to be (e.g. no customizable parameters, like the Vault). In aragonOS@4 we changed this with the lifecycle mechanisms.

Leaving it is safer, particularly if someone forgot to put `initialized()` in their `app.initialize()` function. If it later gets initialized somewhere else (as the app would need to be before it becomes usable from the auth perspective), it would later be impossible to call `app.initialize()` again despite the error.
