### ISSUE TITLE
Add gas check in CI via codecheck

### ISSUE THREAD

**Issue by sohkai** [aragon/aragonOS#544]
See [set up guide for `eth-gas-reporter`'s integration with CodeCheck](https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/codechecks.md).

Not sure how well this works with monorepos, so we can try to set it up here first.

**Comment by cgewecke** [comment]
@sohkai Would it be ok if I self-assign to this issue?  

Also @krzkaczor (the codechecks creator) tells me their service *is* monorepo compatible - will investigate how to modify the gas reporter to take advantage of that this week...

**Comment by sohkai** [comment]
@cgewecke That would be great! [`aragon-apps`](https://github.com/aragon/aragon-apps) is the monorepo, if you want help with testing it there :).
