### ISSUE TITLE
Publish contract mocks used for testing

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/aragonOS#550]
It may be interesting to publish at least some of the contract mocks used for testing. For example, `TimeHelpersMock` is really useful.

**Comment by sohkai** [comment]
Maybe this is something we can include as part of https://github.com/aragon/aragon-apps/issues/379

**Comment by sohkai** [comment]
We can evaluate moving more of the mocks to [`contract-helpers`](https://github.com/aragon/contract-helpers) in the future.
