### ISSUE TITLE
IForwarder: provide ability to mark `forward()` as payable

### ISSUE THREAD

**Issue by sohkai** [aragon/aragonOS#557]
Needed in situations where a forwarder requires some ETH value to be sent. An example would be the applications implementing `IForwarderFee`, e.g. [Tollgate application](https://github.com/aragonone/tollgate), which for now only allows tokens as the fee.

Some potential options:

1. Provide a different `IForwarder` interface, e.g. `IForwarderPayable` (or bundled in `IForwarderFee`), that marks `forward()` as `payable`
1. Change `IForwarder` to be an abstract contract, and mark `forward()` as `payable` but by default reverting if `msg.value > 0`; users would then have to override their own `forward()` and remember to keep the revert if they don't want to accept ETH

It's a little bit ugly, but option 1 seems to be the better choice:

- Does not introduce changes to already deployed contracts
- Most apps will not need their `forward()` function to be `payable`

**Comment by izqui** [comment]
I agree that option 1 is better
