### ISSUE TITLE
Add cron-like capabilites

### ISSUE THREAD

**Issue by vporton** [aragon/aragonOS#573]
Please make possible to repeat an Ethereum transaction filed by a user periodically (e.g. once per month) automatically.

**Comment by sohkai** [comment]
@vporton This is not an issue for the contracts in aragonOS.

This particular issue is an off-chain problem, and can be solved in numerous ways, e.g. using the [Ethereum Alarm Clock](https://www.ethereum-alarm-clock.com/) or writing your own automated backend service (e.g. something like [court-backend](https://github.com/aragonone/court-backend/tree/master/packages/services)).
