### ISSUE TITLE
An app published without a name, cannot be upgraded

### ISSUE THREAD

**Issue by vporton** [aragon/aragonOS#574]
In some reason my app was published without a name (is it because I didn't pin it on IPFS?), despite  I do have `artifact.json` (in my local copy of IPFS) as shown on the screenshot:

![Screenshot from 2020-02-27 22-06-26](https://user-images.githubusercontent.com/2900574/75482405-7081f200-59ad-11ea-9c1a-a6558ad9f4ff.png)

Now when I click it, it goes to https://rinkeby.aragon.org/#/testrewardcourt/apps/installed/undefined and there is no way to upgrade this app!

First explain why it was published with no name.

Second, correct the bug.

**Comment by sohkai** [comment]
@vporton This is not an issue for the contracts in aragonOS; please reach out on Rocketchat or file an issue on the aragonCLI repo.

**Comment by vporton** [comment]
@sohkai I disagree with you.

A bug in external software `aragon-cli` prevents `aragonOS` work as should. This should be protected from in `aragonOS`. So it is a bug in aragonOS!
