### ISSUE TITLE
Pinned an IPFS resource and now cannot upgrade my app locally

### ISSUE THREAD

**Issue by vporton** [aragon/aragonOS#575]
I've pinned an IPFS resource with `ipfs pin ...`.

After this, my app stops to upgrade locally (in browser) after I change the source and re-build it.

Namely this http://localhost:8080/ipfs/QmYgkggqhEy6RcgptZj6FH5uJGEeBpTvHCLafhGWLJXp1s/src.1f47c601.js loads an old version of the file, no matter what I do.

Unpinning this resource does not help.

**Comment by vporton** [comment]
Deleting `dist/` in my package and deleting `~/.ipfs` do not help either.

**Comment by vporton** [comment]
I've found a browser tries to read http://localhost:8080/ipfs/QmYgkggqhEy6RcgptZj6FH5uJGEeBpTvHCLafhGWLJXp1s/artifact.json which takes a big (probably infinite) time.

**Comment by vporton** [comment]
I am unsure if the error was caused by pinning or by whatever else :-(

**Comment by vporton** [comment]
Workaround: Change `appName` in `arapp.json`.

It seems that an IPFS hash was somehow associated with a record in ENS registry.

It is an error, there should be no such association for `--env default` (`rpc`)!

**Comment by sohkai** [comment]
@vporton This is not an issue for the contracts in aragonOS; please reach out on Rocketchat or file an issue on the aragonCLI repo.
