### ISSUE TITLE
My app disappeared

### ISSUE THREAD

**Issue by vporton** [aragon/aragonOS#578]
My app `Reward Court` does not appear in the sidebar:
![Screenshot from 2020-05-20 07-42-32](https://user-images.githubusercontent.com/2900574/82405779-8c0d0e00-9a6d-11ea-857f-88eae6b7c0e7.png)

The app is defined in https://github.com/vporton/courts

Note that I waited several hours.

**Comment by sohkai** [comment]
Are you sure your IPFS content was available? And that no ad blockers are mistakenly blocking your files from being loaded?

On https://rinkeby.aragon.org/#/testrewardcourt4/0x1cf4df5ac50ef5b799e18a31bef5b3b2540cb6d6, the app is loading for me.

**Comment by vporton** [comment]
> Are you sure your IPFS content was available? And that no ad blockers are mistakenly blocking your files from being loaded?

You see, it is on localhost. How can it be not available? It is run by `npm start` that should make it available.

No ad blockers.

> On https://rinkeby.aragon.org/#/testrewardcourt4/0x1cf4df5ac50ef5b799e18a31bef5b3b2540cb6d6, the app is loading for me.

I know. I am now about localhost with `npm start`.

**Comment by sohkai** [comment]
> You see, it is on localhost. How can it be not available? It is run by npm start that should make it available.

I don't know, but since other apps load, it's most likely something to do with your application's content not being available. Are you running the app frontend on localhost too? Are you running against a local development chain? There are a lot of variables at play and more context would help if you'd like us to help solve it :).

**Comment by vporton** [comment]
> > You see, it is on localhost. How can it be not available? It is run by npm start that should make it available.
> 
> I don't know, but since other apps load, it's most likely something to do with your application's content not being available. Are you running the app frontend on localhost too? Are you running against a local development chain? There are a lot of variables at play and more context would help if you'd like us to help solve it :).

Yes, I am running the app frontend on localhost too against a local development chain.

**Comment by sohkai** [comment]
Are you using the buidler plugin or the CLI? If you're using the CLI, are you running in http mode, or does your published content live on IPFS (if so, do you have your local node up?)?

If not using the buidler plugin, I would highly recommend upgrading to it—it will make your local development much, much easier!

**Comment by vporton** [comment]
> Are you using the buidler plugin or the CLI? If you're using the CLI, are you running in http mode, or does your published content live on IPFS (if so, do you have your local node up?)?

CLI.

My content lives on IPFS started by `npm start`.

**Comment by sohkai** [comment]
Do you have the IPFS CID of your published app's latest version? If you have IPFS running locally, can you do a `ipfs ls <cid>` and see if it resolves?

It may also be worth looking at the browser's network tab and seeing what requests are failing—you'll most likely see `artifact.json` and `manifest.json` files being unresolvable and that would point to why your app isn't getting loaded.

Anyhow, again, it would be a good idea to switch to the buidler plugin, which makes all of this much easier and doesn't require IPFS.

**Comment by vporton** [comment]
I don't know how to obtain IPFS CID of an app published at localhost. I have an `artifact.json` and a `manifest.json` pending loading in the browser. When I try `ipfs ls <cid>` with the CID taken from these pending URLs, `ipfs ls <cid>` hangs.

I will try buidler.

**Comment by sohkai** [comment]
Yes, that means your app's content is not resolvable, and that's why we can't load it from the frontend!

You may have to publish again, with your own local node, or pin the content to a service like pinata.

Closing as we've resolved the main issue—for future cases, please use our spectrum channel :).
