### ISSUE TITLE
Support for Diamonds

### ISSUE THREAD

**Issue by mudgen** [aragon/aragonOS#585]
It would be great if aragonOS provided a diamond implementation and/or support for diamonds.

"A diamond is a set of contracts that can access the same storage variables and share the same Ethereum address."

The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

**Comment by sohkai** [comment]
Thanks @mudgen!

We will consider support for Diamonds if we re-architect aragonOS (and can re-open this issue then), but for now, this is currently out of our scope for upgradability / an app framework.
