### ISSUE TITLE
Poll application

### ISSUE THREAD

**Issue by DeveloppSoft** [aragon/aragonOS#92]
Submitting another idea: what about having a polling application similar to votes but with more choices than just yes or no?

**Comment by izqui** [comment]
I can see that being useful for 'informative non-binding' votes in which you only want to see the sentiment about something. For actions to be executed I think it is a much better idea to just have binary votes, which get executed if accepted but don't do anything if not.

**Comment by DeveloppSoft** [comment]
Yeah the idea was to use that for informative votes, such as "which name should we choose?"

**Comment by AaronFoster** [comment]
I think this is a great idea in principle, the issue for me is if it's a separate application it will rarely be used. Also if it's on chain it's unlikely people will pay for non binding votes.

Earlier I'm the year there was talk of integrating a chat app within the ui. Polling there would make alot more sence.

**Comment by DeveloppSoft** [comment]
I can see two uses for an eventual poll application:
1. Informative polls, they do not really need to be performed in chain as @AaronFoster is saying.
2. Decisive polls, I will illustrate that by an example: Alice can make a poll with three choices (or more?) such as allocating 1 ETH to Bob, 2 ETH or 3 ETH.

**Comment by AaronFoster** [comment]
@DeveloppSoft it is much simpler to restrict votes to binary decisions but also less flexible. Not sure why 2 is a problem

**Comment by sohkai** [comment]
Currently being implemented as the Survey app: https://github.com/aragon/aragon-apps/pull/287
